"""
steps/step4_assemble.py — Assemble all chapters into book.md.
Appends references.md if it exists (generated by step4b).

Output: data/book/book.md
"""

import json
import re
import sys
from datetime import date
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from config import RAW_DIR, CHAPTERS_DIR, BOOK_DIR, BOOK_TITLE, BOOK_SUBTITLE


def run():
    print("\n" + "="*60)
    print("STEP 4: Assemble Manuscript")
    print("="*60)

    index_path = RAW_DIR / "playlist_index.json"
    if not index_path.exists():
        print("ERROR: Run Step 1 first.")
        sys.exit(1)

    with open(index_path, encoding="utf-8") as f:
        index = json.load(f)

    # Collect chapters in playlist order
    chapters = []
    missing  = []

    for video in sorted(index, key=lambda v: v.get("playlist_position", 0)):
        folder  = video.get("folder", "")
        ch_path = CHAPTERS_DIR / f"{folder}.md"
        if ch_path.exists() and ch_path.stat().st_size > 200:
            with open(ch_path, encoding="utf-8") as f:
                content = f.read().strip()
            chapters.append({
                "position": video["playlist_position"],
                "title":    video["title"],
                "url":      video.get("url", ""),
                "content":  content,
            })
        else:
            missing.append(video)

    if not chapters:
        print("ERROR: No chapters found. Run Step 3 first.")
        sys.exit(1)

    print(f"\n  Assembling {len(chapters)} chapter(s)...")
    if missing:
        print(f"  WARNING: {len(missing)} video(s) not yet generated")

    # ── Table of Contents ─────────────────────────────────────────────────────
    toc = ["## Table of Contents\n"]
    for ch in chapters:
        heading = _extract_heading(ch["content"], ch["title"])
        anchor  = re.sub(r"[^a-z0-9\s-]", "", heading.lower()).strip().replace(" ", "-")
        toc.append(f"- [{heading}](#{anchor})")

    if missing:
        toc.append("\n**Pending:**")
        for v in missing:
            toc.append(f"- ~~{v['title'][:65]}~~")

    # ── Title page ────────────────────────────────────────────────────────────
    today = date.today().strftime("%B %Y")

    title_page = (
        f"# {BOOK_TITLE}\n"
        f"### {BOOK_SUBTITLE}\n\n"
        f"*Generated {today} from the YouTube playlist*\n\n"
        f"---\n\n"
        f"## About This Book\n\n"
        f"This manuscript is a faithful written record of the video series "
        f'**"{BOOK_TITLE}"**.\n\n'
        f"Every concept, code example, and explanation is derived directly "
        f"from the video transcripts. "
        f"Nothing has been added, inferred, or invented. Where transcripts "
        f"were unclear, the text says so explicitly.\n\n"
        f"Each paragraph includes a citation timestamp that references the "
        f"exact moment in the source video.\n\n"
        f"**Videos covered:** {len(chapters)} of {len(index)} total\n\n"
        f"---\n\n"
        f"{chr(10).join(toc)}\n\n"
        f"---\n"
    )

    # ── Assemble ──────────────────────────────────────────────────────────────
    parts = [title_page]
    for ch in chapters:
        parts.append(ch["content"])
        parts.append("\n\n---\n\n")

    full_book = "\n\n".join(parts)

    # Append references if generated by step4b
    refs_path = BOOK_DIR / "references.md"
    if refs_path.exists():
        with open(refs_path, encoding="utf-8") as f:
            full_book += "\n\n" + f.read().strip()
        print("  Appended references appendix.")

    out_path = BOOK_DIR / "book.md"
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(full_book)

    words = len(full_book.split())
    cites = full_book.count("[▶")
    print(f"\nStep 4 done -- {words:,} words, {cites} citation links, {len(chapters)} chapters.")
    print(f"Output: {out_path}")


def _extract_heading(md: str, fallback: str) -> str:
    for line in md.splitlines():
        if line.startswith("## "):
            return line.lstrip("#").strip()
    return fallback


if __name__ == "__main__":
    run()